[server]
headless = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#070A12"
textColor = "#F1F5F9"
primaryColor = "#3B82F6"
